services:
  postgres:
    image: postgres:16-alpine
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "1234"
      POSTGRES_DB: register
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./course/db/schema.sql:/docker-entrypoint-initdb.d/01-course-schema.sql
      - ./course/db/seed.sql:/docker-entrypoint-initdb.d/02-course-seed.sql
      - ./student/db/schema.sql:/docker-entrypoint-initdb.d/03-student-schema.sql
      - ./student/db/seed.sql:/docker-entrypoint-initdb.d/04-student-seed.sql
      - ./enrollment/db/schema.sql:/docker-entrypoint-initdb.d/05-enrollment-schema.sql
      - ./enrollment/db/seed.sql:/docker-entrypoint-initdb.d/06-enrollment-seed.sql
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d register"]
      interval: 5s
      timeout: 5s
      retries: 5

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: ["CMD-SHELL", "rabbitmq-diagnostics -q check_running"]
      interval: 10s
      timeout: 5s
      retries: 5

  enrollment-service:
    build:
      context: ./enrollment
      dockerfile: dockerfile
    container_name: enrollment-service
    environment:
      DB_HOST: postgres
      RABBITMQ_URL: "amqp://guest:guest@rabbitmq:5672/"
    ports:
      - "8002:8002"
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy

  course-service:
    build:
      context: ./course
      dockerfile: dockerfile
    container_name: course-service
    environment:
      DB_READ_HOST: postgres
      DB_WRITE_HOST: postgres
    ports:
      - "8000:8000"
    depends_on:
      postgres:
        condition: service_healthy

  student-service:
    build:
      context: ./student
      dockerfile: dockerfile
    container_name: student-service
    environment:
      DB_HOST: postgres
    ports:
      - "8001:8001"
    depends_on:
      postgres:
        condition: service_healthy

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - prometheus

volumes:
  postgres_data:
