version: "3.9"

services:

  postgres:
    image: postgres:16-alpine
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "1234"
      POSTGRES_DB: register
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./course/db/schema.sql:/docker-entrypoint-initdb.d/01-course-schema.sql
      - ./course/db/seed.sql:/docker-entrypoint-initdb.d/02-course-seed.sql
      - ./student/db/schema.sql:/docker-entrypoint-initdb.d/03-student-schema.sql
      - ./student/db/seed.sql:/docker-entrypoint-initdb.d/04-student-seed.sql
      - ./enrollment/db/schema.sql:/docker-entrypoint-initdb.d/05-enrollment-schema.sql
      - ./enrollment/db/seed.sql:/docker-entrypoint-initdb.d/06-enrollment-seed.sql
    ports:
      - "5432:5432"
    networks:
      - monitoring
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d register"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 20s

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    restart: unless-stopped
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    networks:
      - monitoring
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "check_running"]
      interval: 30s
      timeout: 10s
      retries: 5

  course-service:
    build:
      context: ./course
      dockerfile: dockerfile
    container_name: course-service
    environment:
      DATABASE_URL: postgres://postgres:1234@postgres:5432/register?sslmode=disable
      RABBITMQ_URL: amqp://guest:guest@rabbitmq:5672/
    ports:
      - "8000:8000"
    networks:
      - monitoring
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy

  student-service:
    build:
      context: ./student
      dockerfile: dockerfile
    container_name: student-service
    environment:
      DATABASE_URL: postgres://postgres:1234@postgres:5432/register?sslmode=disable
    ports:
      - "8001:8001"
    networks:
      - monitoring
    depends_on:
      postgres:
        condition: service_healthy

  enrollment-service:
    build:
      context: ./enrollment
      dockerfile: dockerfile
    container_name: enrollment-service
    environment:
      DATABASE_URL: postgres://postgres:1234@postgres:5432/register?sslmode=disable
      RABBITMQ_URL: amqp://guest:guest@rabbitmq:5672/
    ports:
      - "8002:8002"
    networks:
      - monitoring
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - monitoring

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      GF_SECURITY_ADMIN_PASSWORD: admin
    networks:
      - monitoring
    depends_on:
      - prometheus

  consul:
    image: hashicorp/consul:latest
    container_name: consul
    ports:
      - "8500:8500"
      - "8600:8600/udp"
    command: agent -server -ui -node=server-1 -bootstrap-expect=1 -client=0.0.0.0
    networks:
      - monitoring

volumes:
  postgres_data:

networks:
  monitoring: