# ---- Build Stage ----
FROM golang:1.25-alpine AS builder

WORKDIR /app

# ติดตั้ง git เนื่องจากบาง library ใน go mod ต้องใช้
RUN apk add --no-cache git

# คัดลอกเฉพาะไฟล์ mod ก่อนเพื่อทำ caching layer
COPY go.mod go.sum ./
RUN go mod download


# คัดลอกโค้ดที่เหลือ
COPY . .

RUN go mod tidy
# Build เป็น binary
RUN CGO_ENABLED=0 GOOS=linux go build -o enrollment-service .

# ---- Run Stage ----
FROM alpine:latest

WORKDIR /app

# คัดลอก binary มาจาก stage builder
COPY --from=builder /app/enrollment-service .

# เปิดพอร์ตให้ตรงกับ Gin (8002)
EXPOSE 8002

CMD ["./enrollment-service"]