# ---- Build Stage ----
FROM golang:1.24-alpine AS builder

WORKDIR /app

# Copy go.mod และ go.sum เพื่อทำการ download dependencies ก่อน (ช่วยให้ build เร็วขึ้นในครั้งต่อไป)
COPY go.mod go.sum ./
RUN go mod download

# Copy source code for enrollment service
COPY . .

# Build binary and name it enrollment-service
RUN CGO_ENABLED=0 GOOS=linux go build -o enrollment-service .

# ---- Run Stage (ตัวจริงที่จะเอาไปใช้งาน) ----
FROM alpine:latest

WORKDIR /app

# Copy binary from builder stage
COPY --from=builder /app/enrollment-service .

# Enrollment service listens on port 8080
EXPOSE 8080

# สั่งรันไฟล์
CMD ["./enrollment-service"]