CREATE TABLE IF NOT EXISTS student (
	"student_id" INTEGER NOT NULL UNIQUE,
	"first_name" VARCHAR(255) NOT NULL,
	"last_name" VARCHAR(255) NOT NULL,
	"email" VARCHAR(255) NOT NULL,
	"password" VARCHAR(255) NOT NULL,
	"birthdate" VARCHAR(255) NOT NULL,
	"gender" VARCHAR(255) NOT NULL,
	"year_level" INTEGER NOT NULL,
	"graded_subject" VARCHAR(255) ARRAY,
	PRIMARY KEY("student_id")
);

CREATE TABLE IF NOT EXISTS course (
	"course_id" INTEGER NOT NULL UNIQUE,
	"subject" VARCHAR(255) NOT NULL,
	"credit" INTEGER NOT NULL,
	"section" VARCHAR(255) ARRAY NOT NULL,
	"day_of_week" VARCHAR(255) NOT NULL,
	"start_time" TIME NOT NULL,
	"end_time" TIME NOT NULL,
	"capacity" INTEGER NOT NULL,
	"state" VARCHAR(255) NOT NULL,
	"current_student" VARCHAR(255) ARRAY,
	"prerequisite" VARCHAR(255) ARRAY,
	PRIMARY KEY("course_id")
);


CREATE TABLE IF NOT EXISTS enrollment (
	"enrollment_id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"student_id" INTEGER NOT NULL UNIQUE,
	"course_id" INTEGER ARRAY,
	PRIMARY KEY("enrollment_id")
);
