# ---- Build Stage ----
FROM golang:1.25-alpine AS builder

WORKDIR /app

# Copy go.mod และ go.sum (layer caching)
COPY go.mod go.sum ./
RUN go mod download

# Copy source code ทั้งหมดใน course/
COPY . .

# Build binary (CGO_ENABLED=0 เพื่อให้ได้ static binary ที่รันบน alpine ได้)
RUN go mod tidy
RUN CGO_ENABLED=0 GOOS=linux go build -o course-service .

# ---- Run Stage ----
FROM alpine:latest

WORKDIR /app

# Copy binary จาก build stage
COPY --from=builder /app/course-service .

EXPOSE 8000

CMD ["./course-service"]
